package frames;

import sql.*;
import sql.conexionSQL;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @author Franz Joel Quispe Mamani, Rodrigo Escobar Condori
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        this.setLocationRelativeTo(this);//IMPORTANTE, coloca el formulario al centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        banner = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 130, -1));

        txtNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 210, -1));

        btnIngresar.setBackground(new java.awt.Color(255, 255, 204));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(102, 204, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 210, -1));

        banner.setForeground(new java.awt.Color(51, 255, 102));
        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.jpg"))); // NOI18N
        getContentPane().add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 510, -1));

        jTextField1.setBackground(new java.awt.Color(0, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 510, 70));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgInicioSesion.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        // TODO add your handling code here:
        String user=txtNombreUsuario.getText();
        String pass=txtPassword.getText();

        //select nombreUsuario,password,privilegio from Usuarios where nombreUsuario='Franz Quispe';
        String url = "select nombreUsuario,password,privilegio "
                + "from Usuarios where activo =1 AND nombreUsuario='"+user+"'";
            
        try {    
            //Nos conectamos con la clase conexionSQL
            Connection con= conexionSQL.establecerConexion();
            //Ayuda a precompliar la consulta sql, almacena en este objeto
            PreparedStatement ps = con.prepareStatement(url);
            //Para obtener los datos de columna correspondientes a un fila
            ResultSet rs = ps.executeQuery();
            
            //Permite obtener datos, de la Base de Datos, para eso deben tener los mismos nombres que los campos de la tabla
            if (rs.next()){
                //Si existe el usuario
                //Para obtener el usuario
                String us=rs.getString("nombreUsuario");
                //Para obtener su contraseña
                String pas=rs.getString("password");
                //Para obtener que privilegio tiene el usuario
                String priv=rs.getString("privilegio");
                
                //Verificamos el password ingresado al de la tabla
                if(pass.equals(pas)){
                    //Envia al jframe correspondiente segun el privilegio
                    //Si el privilegio es de DBA, manda a el acceso total de todas las ventanas
                    if(priv.equals("DBA")){
                        frmDBA ventanaDBA = new frmDBA();
                        ventanaDBA.setVisible(true);
                        this.setVisible(false);
                    //Si el privilegio es de Supervisor manda a las ventanas necesarias para el
                    }else if(priv.equals("Supervisor")){
                        frmSupervisor ventanaSupervisor = new frmSupervisor();
                        ventanaSupervisor.setVisible(true);        
                    }        
                }else{
                    JOptionPane.showMessageDialog(null, "La contraseña no es la correcta", "Contraseña no válida",JOptionPane.WARNING_MESSAGE);
                }
            }else{
                //El usuario no existe
                JOptionPane.showMessageDialog(null, "El usuario ingresado no existe en la Base de Datos", "Usuario no existente",JOptionPane.WARNING_MESSAGE);
            }   
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
