
package frames;

/**
 * @author Franz Joel Quispe Mamani, Rodrigo Escobar Condori
 */
public class vtNewtonInterp extends javax.swing.JInternalFrame {

    /**
     * Creates new form vtNewtonInterp
     */
    public vtNewtonInterp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formulaNewton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValorInterpolacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnResolver = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNuevoPunto = new javax.swing.JTextField();

        setBackground(new java.awt.Color(231, 235, 235));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Interpolación lineal de Newton");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formulaNewton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NewtonFormula.png"))); // NOI18N
        getContentPane().add(formulaNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 33, 476, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("La fórmula de Interpolación Lineal de Newton es:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 64, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 245, 238));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("El problema planteado es:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 117, -1, -1));

        txtValorInterpolacion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtValorInterpolacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 90, -1));

        jLabel4.setBackground(new java.awt.Color(255, 245, 238));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Obteniendo el nuevo punto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("La cantidad de estudiantes que asisten en la carrera de Psicomotricidad, los días 16, 17 de septiembre sigue la siguiente tabla:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 149, 1050, 53));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tablaNew.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 80));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Se quiere saber la cantidad de estudiantes que habia en el 15 de septiembre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tablaNew2.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 400, 120));

        btnResolver.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, -1));

        txtResultado.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, 100, -1));

        jLabel10.setBackground(new java.awt.Color(255, 245, 238));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("2x - 3");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 60, -1));

        jLabel11.setBackground(new java.awt.Color(255, 245, 238));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("x");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 245, 238));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Ingresamos el valor de interpolación:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 245, 238));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("El modelo matemático:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 200, -1));

        jLabel8.setBackground(new java.awt.Color(255, 245, 238));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("El resultado es:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        txtNuevoPunto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNuevoPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNuevoPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 500, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
        int total=Integer.parseInt(txtValorInterpolacion.getText());
        total *=22;
        total -=203;
        txtResultado.setText(total+"");
        txtNuevoPunto.setText("("+txtValorInterpolacion.getText()+","+total+")");    
    }//GEN-LAST:event_btnResolverActionPerformed

    private void txtNuevoPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoPuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoPuntoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResolver;
    private javax.swing.JLabel formulaNewton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtNuevoPunto;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtValorInterpolacion;
    // End of variables declaration//GEN-END:variables
}
